### ISSUE TITLE
Problema com o khan

### ISSUE THREAD

**Issue by Abdala4ever** [DarkMod3/CMSP-Plataformas-Hacks#1]
O script do khan academy não tá funcionando, dá erro 
![image](https://github.com/user-attachments/assets/8e5642c4-fe34-49ba-9603-efb0b33f6f1a)
![image](https://github.com/user-attachments/assets/77915331-350b-4926-b03b-2585ca901fa0)

**Comment by FellipeQS** [comment]
Verdade o meu tambem começou a dar erro

**Comment by DarkMod3** [comment]
O Khan concertou o script mais logo logo eu lança o novo script atualizado!
