### ISSUE TITLE
Media de tempo

### ISSUE THREAD

**Issue by Tiitico** [DarkMod3/CMSP-Plataformas-Hacks#23]
Acredito q se fosse feita uma media do tempo q o aluno demora em cada atividade, evitaria anormalidades no tempo, eu tenho uma media de 3 minutos por questão, como o script finaliza entre 1 minuto a 0 segundos, isso causa uma anormalidade.

**Comment by DarkMod3** [comment]
Estamos trabalhando nisso obrigado pela opnião
