### ISSUE TITLE
Como uso os Scripts? (Speak)

### ISSUE THREAD

**Issue by Hairuddis** [DarkMod3/CMSP-Plataformas-Hacks#26]
Abri o site, e diz que o script está copiado, mas não tenho ideia de onde colo, já tentei o console, e até mesmo salvar uma página nova favorita. Simplesmente não sei.

**Comment by DarkMod3** [comment]
Simples: Você salva o script como um link do favoritos, abre o site do speak e alguma tarefa e depois é só clicar no favorito com o script
