### ISSUE TITLE
Vamo

### ISSUE THREAD

**Issue by Pietrobesson** [DarkMod3/CMSP-Plataformas-Hacks#28]
<a href="https://bit.ly/CMSP-Plataformas-Hacks"><img width="15%" src="https://i.imgur.com/JNmC69a.png"/></a>
    &#8287;

**Comment by Pietrobesson** [comment]
<a href="https://bit.ly/CMSP-Plataformas-Hacks"><img width="15%" src="https://i.imgur.com/JNmC69a.png"/></a>
    &#8287;

**Comment by DarkMod3** [comment]
?
