### ISSUE TITLE
Erro ao fazer as atividades, atividades sendo salvas como rascunho

### ISSUE THREAD

**Issue by rgrla** [DarkMod3/CMSP-Plataformas-Hacks#4]
![image](https://github.com/user-attachments/assets/fac2250f-96fe-44e9-a934-496e8bed8ac9)
![image](https://github.com/user-attachments/assets/6766a164-3aea-4ae6-ae62-e3c7ebef1bf5)

Foi mal se o issue é redundante, ótimo programa, cara

**Comment by DarkMod3** [comment]
Não é um "erro" é que as vezes ele faz a atividade muito rapido e acaba pulando a parte de enviar 

![image](https://github.com/user-attachments/assets/c3776493-0e59-494f-923b-2e381746728f)

As unicas que ficam em rascunho são as redações porque de resto elas são cloncluidas depois de um tempo

**Comment by rgrla** [comment]
> Não é um "erro" é que as vezes ele faz a atividade muito rapido e acaba pulando a parte de enviar 

Não é pra teimar, testei de novo e funcionou, mas quando chequei os rascunhos eles não tinham resposta selecionada, é visual só? Obrigado pela ajuda, mano 🤗

**Comment by DarkMod3** [comment]
Bom provavelmente deve ter acontecido algum erro com você infelizmente as atividades que ficaram em rascunho você vai ter que fazer manualmente KKKK ( Foi mal pelo erro mano )
