### ISSUE TITLE
o hack do khan parou de funcionar

### ISSUE THREAD

**Issue by Leo2024a** [DarkMod3/CMSP-Plataformas-Hacks#8]
Ola entao eu fui fazer o khan hoje e quando tentei fazer a atividade ele parou ele so carrega e da erro de produto nao genuino

**Comment by Kingzincmd** [comment]
o cmsp também desse de ontem te redirecionando para o discord

**Comment by Kingzincmd** [comment]
> o cmsp também desse de ontem te redirecionando para o discord

@DarkMod3

**Comment by xoxitoss** [comment]
> Ola entao eu fui fazer o khan hoje e quando tentei fazer a atividade ele parou ele so carrega e da erro de produto nao genuino

oioi, ele falou pra mim uma vez que era só botar o nome de usuário do khan que funciona, é aquele nome com o @, se não tiver nada, bota um nome e dps usa o hack

**Comment by xoxitoss** [comment]
aoba, aparentemente deu um erro no servidor do hack do cmsp, eu abri pelo celular e não funcionou, não testei no pc ainda, mas se for isso, ta de boa

![Screenshot_20241018-144219](https://github.com/user-attachments/assets/ba5f2e93-83e9-4851-95d0-1424bea9e8ea)

**Comment by DarkMod3** [comment]
Calma gente eu voltei

**Comment by DarkMod3** [comment]
> aoba, aparentemente deu um erro no servidor do hack do cmsp, eu abri pelo celular e não funcionou, não testei no pc ainda, mas se for isso, ta de boa
> 
> ![Screenshot_20241018-144219](https://private-user-images.githubusercontent.com/185021070/377963002-ba5f2e93-83e9-4851-95d0-1424bea9e8ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NjM2MTEsIm5iZiI6MTcyOTQ2MzMxMSwicGF0aCI6Ii8xODUwMjEwNzAvMzc3OTYzMDAyLWJhNWYyZTkzLTgzZTktNDg1MS05NWQwLTE0MjRiZWE5ZThlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQyMjI4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODIxMWI0OTgzOGU3ZDI5ZTQyNjQzNzkxMzA2YTY1MDUyZWU2MTlhYzk1MTM3ZDM1OTJkMjhmMjIyMzZhODE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6qWnSW4MujWG5DRLBRwX4z6Hx2a7QjNb_1uFM6L7fss)

Isso foi porque ele trocou a URL do site a nova ja ta ai Repositorio

**Comment by DarkMod3** [comment]
> > o cmsp também desse de ontem te redirecionando para o discord
> 
> @DarkMod3

Isso é porque o marcos adicionou essa verificação ao site, agora para ultilizar o site precisa de logar com o discord

**Comment by DarkMod3** [comment]
> Ola entao eu fui fazer o khan hoje e quando tentei fazer a atividade ele parou ele so carrega e da erro de produto nao genuino

Tenta atulizar a pagina e usar o Script novo que eu acabei de postar

**Comment by DarkMod3** [comment]
Caso precisem de outra ajuda basta perguntarem que eu irei responder 😃

**OBS:** Não tinha respondido nenhuma pergunta porque minha semana ta meio corrida to tendo que fazer auto-escola KKKK

**Comment by xoxitoss** [comment]
> Caso precisem de outra ajuda basta perguntarem que eu irei responder 😃
> 
> **OBS:** Não tinha respondido nenhuma pergunta porque minha semana ta meio corrida to tendo que fazer auto-escola KKKK
> 
> @xoxitoss @Leo2024a @Kingzincmd

eu imagino, que coincidência, tbm vou fazer autoescola daqui 1 mês :D boa aula pra vc

**Comment by DarkMod3** [comment]
> > Caso precisem de outra ajuda basta perguntarem que eu irei responder 😃
> > **OBS:** Não tinha respondido nenhuma pergunta porque minha semana ta meio corrida to tendo que fazer auto-escola KKKK
> > @xoxitoss @Leo2024a @Kingzincmd
> 
> eu imagino, que coincidência, tbm vou fazer autoescola daqui 1 mês :D boa aula pra vc

Vlw tomara que a gente passe KKKKK
